package com.example.tm__mt.ecoquiz;

/**
 * Created by tm__mt
 *
 * Holds a structure of QuestionWebPath table and provides basic functions/queries to that table.
 */
public class TQuestionWebPath {
    //table structure: table and column names
    private static final String TABLE_NAME          = "QuestionWebPath";
    private static final String COL_QUESTION_ID     = "QUESTION_ID";
    private static final String COL_PATH1           = "PATH1";
    private static final String COL_PATH2           = "PATH2";
    private static final String COL_PATH3           = "PATH3";
    private static final String COL_PATH4           = "PATH4";
    private static final String COL_PATH5           = "PATH5";
    private static final String COL_PATH6           = "PATH6";

    private static final String CREATE_QUERY = "CREATE TABLE IF NOT EXISTS " + getTableName() + " ( "
            + " QUESTION_ID       INTEGER NOT NULL "
            + ",PATH1             TEXT NOT NULL "
            + ",PATH2             TEXT NOT NULL "
            + ",PATH3             TEXT NOT NULL "
            + ",PATH4             TEXT NOT NULL "
            + ",PATH5             TEXT NOT NULL "
            + ",PATH6             TEXT NOT NULL "
            + ",PRIMARY KEY (QUESTION_ID) "
            + ",FOREIGN KEY(`QUESTION_ID`) REFERENCES Question(ID) "
            + ");";
    private static final String DROP_QUERY = "DROP " + getTableName() + " TABLE;";

    //table values; content should be generated by other tool and copy/paste here
    private static String [][] values = {
             {"1", "http://ecoquiz.pe.hu/logos%size%blueangel.9.png", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png", "http://ecoquiz.pe.hu/logos%size%energycities.9.png", "http://ecoquiz.pe.hu/logos%size%energycities.9.png", "http://ecoquiz.pe.hu/logos%size%epa.9.png", "http://ecoquiz.pe.hu/logos%size%fsc.9.png"}
            ,{"2", "http://ecoquiz.pe.hu/logos%size%fsc.9.png", "http://ecoquiz.pe.hu/logos%size%blueangel.9.png", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png", "http://ecoquiz.pe.hu/logos%size%greenseal.9.png", "http://ecoquiz.pe.hu/logos%size%planetpositive.9.png", "http://ecoquiz.pe.hu/logos%size%epa.9.png"}
            ,{"3", "http://ecoquiz.pe.hu/logos%size%epa.9.png", "http://ecoquiz.pe.hu/logos%size%fsc.9.png", "http://ecoquiz.pe.hu/logos%size%blueangel.9.png", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png", "http://ecoquiz.pe.hu/logos%size%energycities.9.png", "http://ecoquiz.pe.hu/logos%size%greenseal.9.png"}
            ,{"4", "http://ecoquiz.pe.hu/logos%size%planetpositive.9.png", "http://ecoquiz.pe.hu/logos%size%epa.9.png", "http://ecoquiz.pe.hu/logos%size%fsc.9.png", "http://ecoquiz.pe.hu/logos%size%blueangel.9.png", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png", "http://ecoquiz.pe.hu/logos%size%energycities.9.png"}
            ,{"5", "http://ecoquiz.pe.hu/logos%size%energycities.9.png", "http://ecoquiz.pe.hu/logos%size%greenseal.9.png", "http://ecoquiz.pe.hu/logos%size%epa.9.png", "http://ecoquiz.pe.hu/logos%size%fsc.9.png", "http://ecoquiz.pe.hu/logos%size%blueangel.9.png", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png"}
            ,{"6", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png", "http://ecoquiz.pe.hu/logos%size%energycities.9.png", "http://ecoquiz.pe.hu/logos%size%greenseal.9.png", "http://ecoquiz.pe.hu/logos%size%epa.9.png", "http://ecoquiz.pe.hu/logos%size%ecolabel.9.png", "http://ecoquiz.pe.hu/logos%size%planetpositive.9.png"}
    };

    public static String insertQuery(int i) {
        if ( values[i][0].equals("") ||
             values[i][1].equals("") ||
             values[i][2].equals("") ||
             values[i][3].equals("") ||
             values[i][4].equals("") ||
             values[i][5].equals("") ||
             values[i][6].equals("") )
            return null;

        return "INSERT INTO " + getTableName() + " VALUES " + " ("
                +         values[i][0]
                + ", '" + values[i][1] + "'"
                + ", '" + values[i][2] + "'"
                + ", '" + values[i][3] + "'"
                + ", '" + values[i][4] + "'"
                + ", '" + values[i][5] + "'"
                + ", '" + values[i][6] + "'"
                + ");";
    }

    public static String getTableName() {
        return TABLE_NAME;
    }

    public static String getColQuestionId() {
        return COL_QUESTION_ID;
    }

    public static String getColPath1() {
        return COL_PATH1;
    }

    public static String getColPath2() {
        return COL_PATH2;
    }

    public static String getColPath3() {
        return COL_PATH3;
    }

    public static String getColPath4() {
        return COL_PATH4;
    }

    public static String getColPath5() {
        return COL_PATH5;
    }

    public static String getColPath6() {
        return COL_PATH6;
    }

    public static String getCreateQuery() {
        return CREATE_QUERY;
    }

    public static String getDropQuery() {
        return DROP_QUERY;
    }

    public static int getValuesNumber() {
        return values.length;
    }
}
